function [scenario, egoCar] = HelperCreateDrivingScenario5()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 04-May-2020 21:39:17

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-33 58.3 0;
    20.5 18.9 0;
    61.7 -35.8 0];
laneSpecification = lanespec(3, 'Width', 5);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego car
egoCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-33.3 58.5 0]);
waypoints = [-33.3 58.5 0;
    -17.2 48.1 0;
    -1.8 38.1 0;
    9.1 33.4 0;
    24.8 22.3 0;
    35.7 10.3 0;
    46.8 -4.9 0;
    53.6 -20.1 0;
    55.6 -26 0;
    61.9 -35.3 0];
speed = 30;
trajectory(egoCar, waypoints, speed);

