function [scenario, egoCar] = HelperCreateDrivingScenario7()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 04-May-2020 21:48:13

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-33 58.3 0;
    20.5 18.9 0;
    61.7 -35.8 0];
laneSpecification = lanespec(3, 'Width', 5);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego car
egoCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-33.3 58.5 0]);
waypoints = [-33.3 58.5 0;
    -12 45.6 0;
    7.3 35.6 0;
    27 17.3 0;
    34.1 -3.6 0;
    46.8 -13.5 0;
    55.1 -25.3 0;
    62.2 -36 0];
speed = 30;
trajectory(egoCar, waypoints, speed);

