function [scenario, egoCar] = HelperCreateDrivingScenario1()
% createDrivingScenario Returns the drivingScenario defined in the Designer
% helperCreateDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.2.

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    15 0 0;
    30 0 0;
    45 0 0;
    60 0 0;
    91.29 2.462 0;
    121.8 9.789 0;
    150.8 21.8 0;
    177.6 38.2 0;
    201.4 58.58 0;
    225.3 78.96 0;
    252 95.36 0;
    281 107.4 0;
    311.6 114.7 0;
    342.8 117.2 0;
    357.8 117.2 0;
    372.8 117.2 0;
    387.8 117.2 0;
    402.8 117.2 0];
laneSpecification = lanespec(3, 'Width', 3.2);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego car
egoCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [402.401155168584 117.157266411189 0], ...
    'FrontOverhang', 0.9);
waypoints = [0 0 0;
    15 0 0;
    30 0 0;
    45 0 0;
    60 0 0;
    91.2868930080462 2.46233188097244 0;
    121.803398874989 9.7886967409693 0;
    150.798099947909 21.7986951623264 0;
    177.557050458495 38.1966011250105 0;
    199.79 60.55 0.01;
    222.15 80.79 0.01;
    251.37 98.1 0.01;
    280.9 108 0;
    311.555819466573 114.694955644409 0;
    342.842712474619 117.157287525381 0;
    357.842712474619 117.157287525381 0;
    372.842712474619 117.157287525381 0;
    387.842712474619 117.157287525381 0;
    402.842712474619 117.157287525381 0];
speed = 10;
trajectory(egoCar, waypoints, speed);

trajectory(egoCar, waypoints, speed);

