function [scenario, egoCar] = HelperCreateDrivingScenario4()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 04-May-2020 21:33:53

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0.7 22.2 0;
    22.7 1.5 0;
    38.5 -5.2 0;
    44.1 -23.1 0];
laneSpecification = lanespec(2, 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego car
egoCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0.6 19.5 0]);
waypoints = [0.6 19.5 0;
    7.2 10.8 0;
    14.9 3.6 0;
    23 -0.9 0;
    28.8 1.1 0;
    34.7 0 0;
    40.1 -4 0;
    43.6 -8.7 0;
    45.3 -16.3 0;
    46.1 -22.9 0];
speed = 30;
trajectory(egoCar, waypoints, speed);

