function [scenario, egoCar] = HelperCreateDrivingScenario6()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 04-May-2020 21:44:33

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-33 58.3 0;
    20.5 18.9 0;
    61.7 -35.8 0];
laneSpecification = lanespec(3, 'Width', 5);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego car
egoCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-33.3 58.5 0]);
waypoints = [-33.3 58.5 0;
    -19.4 49.9 0;
    -8.1 45.4 0;
    4.1 38.1 0;
    11.4 27 0;
    24.3 15.2 0;
    27 4.4 0;
    36.8 -8.3 0;
    47.4 -24 0;
    57.2 -38 0];
speed = 30;
trajectory(egoCar, waypoints, speed);

