function [scenario, egoCar] = HelperCreateDrivingScenario8()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.5 and Automated Driving System Toolbox 1.3.
% Generated on: 04-May-2020 21:50:41

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-33 58.3 0;
    20.5 18.9 0;
    61.7 -35.8 0];
laneSpecification = lanespec(3, 'Width', 5);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego car
egoCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-33.3 58.5 0]);
waypoints = [-33.3 58.5 0;
    -24 47 0;
    -3.8 45.9 0;
    5.5 25.7 0;
    17.3 23 0;
    24.3 14.3 0;
    35.9 9.4 0;
    47.9 -4.9 0;
    55.1 -24.7 0;
    61.9 -35.5 0];
speed = 30;
trajectory(egoCar, waypoints, speed);

